// Translation data for all languages
const translations = {
    sq: {
        'salad': 'Salat',
        'edamame': 'Edamame',
        'sushi-roll': 'Sushi Roll',
        'combo': 'Sushi Combo',
        'tartare': 'Tartare',
        'tataki': 'Tataki',
        'poke': 'Poke Bowl',
        'nigiri': 'Nigiri (1 COPË)',
        'maki': 'Maki',
        'sashimi': 'Sashimi Set',
        'footer': 'Shijoni pjelelave tuaja!',
        
        'kani-salad': 'Kani Salat',
        'yousun-salad': 'Yousun Salat',
        'hot-edamame': 'Edamame i Nxehtë',
        'spicy-edamame': 'Edamame Pikant',
        'demi-special': 'Demi Special Roll',
        'caterpillar': 'Caterpillar Roll',
        'ebi-ten': 'Ebi Ten Roll',
        'california': 'California Roll',
        'spicy-tuna': 'Spicy Tuna Roll',
        'sake-ten': 'Sake Ten Roll',
        'samurai': 'Samurai Roll',
        'rainbow': 'Rainbow Roll',
        'fire-salmon': 'Fire Salmon Roll',
        'sea-bass-ponzu': 'Sea Bass Ponzu Roll',
        'two-way': 'Two Way Roll',
        'tokyo': 'Tokyo Roll',
        'fish-chips': 'Fish Chips Roll',
        'squid': 'Baby Squid Roll',
        'philly': 'Philly Roll',
        'city': 'City Roll',
        'hot-love-20': 'Hot Love Combo 20 copë',
        'hot-love-40': 'Hot Love Combo 40 copë',
        'hot-love-72': 'Hot Love Combo 72 copë',
        'salmon-tartare': 'Salmon Tartar',
        'seabass-tartare': 'Sea Bass Tartar',
        'tuna-tartare': 'Tuna Tartar',
        'salmon-tataki': 'Salmon Tataki',
        'seabass-tataki': 'Sea Bass Tataki',
        'tuna-tataki': 'Tuna Tataki',
        'poke-salmon': 'Poke Bowl Salmon',
        'ton': 'Ton',
        'salmon-nigiri': 'Salmon',
        'salmon-avo': 'Salmon Avocado',
        'lavrak': 'Lavrak',
        'unagi': 'Unagi',
        'cucumber-maki': 'Cucumber Maki 6 copë',
        'maguro-maki': 'Maguro Maki 6 copë',
        'ebi-maki': 'Ebi Tem 6 copë',
        'kani-maki': 'Kani Maki 6 copë',
        'unagi-maki': 'Unagi Maki 6 copë',
        'avocado-sake': 'Avocado Sake Maki 6 copë',
        'sake-maki': 'Sake Maki 6 copë',
        'unagi-avocado': 'Unagi Avocado 6 copë',
        'salmon-sashimi': 'Salmon Sashimi Set (Salmon 6)',
        'tuna-sashimi': 'Tuna Sashimi Set (Tuna 6)',
        'lavrak-sashimi': 'Lavrak Sashimi Set (Lavrak 6)',
        'salmon-avo-sashimi': 'Salmon Avocado Sashimi Set (Salmon 6, Avocado 6)',
        'sashimi-mix': 'Sashimi Mix Set (Salmon 2, Lavrak 2, Tuna 2, Avocado)',
    },
    en: {
        'salad': 'Salad',
        'edamame': 'Edamame',
        'sushi-roll': 'Sushi Roll',
        'combo': 'Sushi Combo',
        'tartare': 'Tartare',
        'tataki': 'Tataki',
        'poke': 'Poke Bowl',
        'nigiri': 'Nigiri (1 PIC)',
        'maki': 'Maki',
        'sashimi': 'Sashimi Set',
        'footer': 'Enjoy your meal!',
        
        'kani-salad': 'Kani Salad',
        'yousun-salad': 'Yousun Salad',
        'hot-edamame': 'Hot Edamame',
        'spicy-edamame': 'Spicy Edamame',
        'demi-special': 'Demi Special Roll',
        'caterpillar': 'Caterpillar Roll',
        'ebi-ten': 'Ebi Ten Roll',
        'california': 'California Roll',
        'spicy-tuna': 'Spicy Tuna Roll',
        'sake-ten': 'Sake Ten Roll',
        'samurai': 'Samurai Roll',
        'rainbow': 'Rainbow Roll',
        'fire-salmon': 'Fire Salmon Roll',
        'sea-bass-ponzu': 'Sea Bass Ponzu Roll',
        'two-way': 'Two Way Roll',
        'tokyo': 'Tokyo Roll',
        'fish-chips': 'Fish Chips Roll',
        'squid': 'Baby Squid Roll',
        'philly': 'Philly Roll',
        'city': 'City Roll',
        'hot-love-20': 'Hot Love Combo 20 piece',
        'hot-love-40': 'Hot Love Combo 40 piece',
        'hot-love-72': 'Hot Love Combo 72 piece',
        'salmon-tartare': 'Salmon Tartar',
        'seabass-tartare': 'Sea Bass Tartar',
        'tuna-tartare': 'Tuna Tartar',
        'salmon-tataki': 'Salmon Tataki',
        'seabass-tataki': 'Sea Bass Tataki',
        'tuna-tataki': 'Tuna Tataki',
        'poke-salmon': 'Poke Bowl Salmon',
        'ton': 'Ton',
        'salmon-nigiri': 'Salmon',
        'salmon-avo': 'Salmon Avocado',
        'lavrak': 'Sea Bass',
        'unagi': 'Unagi',
        'cucumber-maki': 'Cucumber Maki 6 piece',
        'maguro-maki': 'Maguro Maki 6 piece',
        'ebi-maki': 'Ebi Tem 6 piece',
        'kani-maki': 'Kani Maki 6 piece',
        'unagi-maki': 'Unagi Maki 6 piece',
        'avocado-sake': 'Avocado Sake Maki 6 piece',
        'sake-maki': 'Sake Maki 6 piece',
        'unagi-avocado': 'Unagi Avocado 6 piece',
        'salmon-sashimi': 'Salmon Sashimi Set (Salmon 6)',
        'tuna-sashimi': 'Tuna Sashimi Set (Tuna 6)',
        'lavrak-sashimi': 'Sea Bass Sashimi Set (Sea Bass 6)',
        'salmon-avo-sashimi': 'Salmon Avocado Sashimi Set (Salmon 6, Avocado 6)',
        'sashimi-mix': 'Sashimi Mix Set (Salmon 2, Sea Bass 2, Tuna 2, Avocado)',
    },
    it: {
        'salad': 'Insalata',
        'edamame': 'Edamame',
        'sushi-roll': 'Sushi Roll',
        'combo': 'Combo Sushi',
        'tartare': 'Tartare',
        'tataki': 'Tataki',
        'poke': 'Ciotola Poke',
        'nigiri': 'Nigiri (1 PEZZO)',
        'maki': 'Maki',
        'sashimi': 'Set Sashimi',
        'footer': 'Buon appetito!',
        
        'kani-salad': 'Insalata di Kani',
        'yousun-salad': 'Insalata Yousun',
        'hot-edamame': 'Edamame Caldo',
        'spicy-edamame': 'Edamame Piccante',
        'demi-special': 'Demi Special Roll',
        'caterpillar': 'Caterpillar Roll',
        'ebi-ten': 'Ebi Ten Roll',
        'california': 'California Roll',
        'spicy-tuna': 'Spicy Tuna Roll',
        'sake-ten': 'Sake Ten Roll',
        'samurai': 'Samurai Roll',
        'rainbow': 'Rainbow Roll',
        'fire-salmon': 'Fire Salmon Roll',
        'sea-bass-ponzu': 'Sea Bass Ponzu Roll',
        'two-way': 'Two Way Roll',
        'tokyo': 'Tokyo Roll',
        'fish-chips': 'Fish Chips Roll',
        'squid': 'Baby Squid Roll',
        'philly': 'Philly Roll',
        'city': 'City Roll',
        'hot-love-20': 'Hot Love Combo 20 pezzi',
        'hot-love-40': 'Hot Love Combo 40 pezzi',
        'hot-love-72': 'Hot Love Combo 72 pezzi',
        'salmon-tartare': 'Tartare di Salmone',
        'seabass-tartare': 'Tartare di Branzino',
        'tuna-tartare': 'Tartare di Tonno',
        'salmon-tataki': 'Salmon Tataki',
        'seabass-tataki': 'Sea Bass Tataki',
        'tuna-tataki': 'Tuna Tataki',
        'poke-salmon': 'Ciotola Poke Salmone',
        'ton': 'Ton',
        'salmon-nigiri': 'Salmone',
        'salmon-avo': 'Salmone Avocado',
        'lavrak': 'Branzino',
        'unagi': 'Unagi',
        'cucumber-maki': 'Cucumber Maki 6 pezzi',
        'maguro-maki': 'Maguro Maki 6 pezzi',
        'ebi-maki': 'Ebi Tem 6 pezzi',
        'kani-maki': 'Kani Maki 6 pezzi',
        'unagi-maki': 'Unagi Maki 6 pezzi',
        'avocado-sake': 'Avocado Sake Maki 6 pezzi',
        'sake-maki': 'Sake Maki 6 pezzi',
        'unagi-avocado': 'Unagi Avocado 6 pezzi',
        'salmon-sashimi': 'Set Sashimi di Salmone (Salmone 6)',
        'tuna-sashimi': 'Set Sashimi di Tonno (Tonno 6)',
        'lavrak-sashimi': 'Set Sashimi di Branzino (Branzino 6)',
        'salmon-avo-sashimi': 'Set Sashimi Salmone Avocado (Salmone 6, Avocado 6)',
        'sashimi-mix': 'Set Sashimi Mix (Salmone 2, Branzino 2, Tonno 2, Avocado)',
    },
    de: {
        'salad': 'Salat',
        'edamame': 'Edamame',
        'sushi-roll': 'Sushi Rolle',
        'combo': 'Sushi Combo',
        'tartare': 'Tartare',
        'tataki': 'Tataki',
        'poke': 'Poke Schüssel',
        'nigiri': 'Nigiri (1 STÜCK)',
        'maki': 'Maki',
        'sashimi': 'Sashimi Set',
        'footer': 'Guten Appetit!',
        
        'kani-salad': 'Kani Salat',
        'yousun-salad': 'Yousun Salat',
        'hot-edamame': 'Heiße Edamame',
        'spicy-edamame': 'Scharfe Edamame',
        'demi-special': 'Demi Special Rolle',
        'caterpillar': 'Caterpillar Rolle',
        'ebi-ten': 'Ebi Ten Rolle',
        'california': 'California Rolle',
        'spicy-tuna': 'Spicy Tuna Rolle',
        'sake-ten': 'Sake Ten Rolle',
        'samurai': 'Samurai Rolle',
        'rainbow': 'Rainbow Rolle',
        'fire-salmon': 'Fire Salmon Rolle',
        'sea-bass-ponzu': 'Sea Bass Ponzu Rolle',
        'two-way': 'Two Way Rolle',
        'tokyo': 'Tokyo Rolle',
        'fish-chips': 'Fish Chips Rolle',
        'squid': 'Baby Squid Rolle',
        'philly': 'Philly Rolle',
        'city': 'City Rolle',
        'hot-love-20': 'Hot Love Combo 20 Stück',
        'hot-love-40': 'Hot Love Combo 40 Stück',
        'hot-love-72': 'Hot Love Combo 72 Stück',
        'salmon-tartare': 'Lachs Tartare',
        'seabass-tartare': 'Wolfsbarsch Tartare',
        'tuna-tartare': 'Thunfisch Tartare',
        'salmon-tataki': 'Lachs Tataki',
        'seabass-tataki': 'Wolfsbarsch Tataki',
        'tuna-tataki': 'Thunfisch Tataki',
        'poke-salmon': 'Poke Schüssel Lachs',
        'ton': 'Ton',
        'salmon-nigiri': 'Lachs',
        'salmon-avo': 'Lachs Avocado',
        'lavrak': 'Wolfsbarsch',
        'unagi': 'Unagi',
        'cucumber-maki': 'Gurken Maki 6 Stück',
        'maguro-maki': 'Maguro Maki 6 Stück',
        'ebi-maki': 'Ebi Tem 6 Stück',
        'kani-maki': 'Kani Maki 6 Stück',
        'unagi-maki': 'Unagi Maki 6 Stück',
        'avocado-sake': 'Avocado Sake Maki 6 Stück',
        'sake-maki': 'Sake Maki 6 Stück',
        'unagi-avocado': 'Unagi Avocado 6 Stück',
        'salmon-sashimi': 'Lachs Sashimi Set (Lachs 6)',
        'tuna-sashimi': 'Thunfisch Sashimi Set (Thunfisch 6)',
        'lavrak-sashimi': 'Wolfsbarsch Sashimi Set (Wolfsbarsch 6)',
        'salmon-avo-sashimi': 'Lachs Avocado Sashimi Set (Lachs 6, Avocado 6)',
        'sashimi-mix': 'Sashimi Mix Set (Lachs 2, Wolfsbarsch 2, Thunfisch 2, Avocado)',
    },
    fr: {
        'salad': 'Salade',
        'edamame': 'Edamame',
        'sushi-roll': 'Rouleau Sushi',
        'combo': 'Combo Sushi',
        'tartare': 'Tartare',
        'tataki': 'Tataki',
        'poke': 'Bol Poke',
        'nigiri': 'Nigiri (1 PIÈCE)',
        'maki': 'Maki',
        'sashimi': 'Set Sashimi',
        'footer': 'Bon appétit!',
        
        'kani-salad': 'Salade de Kani',
        'yousun-salad': 'Salade Yousun',
        'hot-edamame': 'Edamame Chaud',
        'spicy-edamame': 'Edamame Épicé',
        'demi-special': 'Rouleau Demi Special',
        'caterpillar': 'Rouleau Caterpillar',
        'ebi-ten': 'Rouleau Ebi Ten',
        'california': 'Rouleau California',
        'spicy-tuna': 'Rouleau Spicy Tuna',
        'sake-ten': 'Rouleau Sake Ten',
        'samurai': 'Rouleau Samurai',
        'rainbow': 'Rouleau Rainbow',
        'fire-salmon': 'Rouleau Fire Salmon',
        'sea-bass-ponzu': 'Rouleau Sea Bass Ponzu',
        'two-way': 'Rouleau Two Way',
        'tokyo': 'Rouleau Tokyo',
        'fish-chips': 'Rouleau Fish Chips',
        'squid': 'Rouleau Baby Squid',
        'philly': 'Rouleau Philly',
        'city': 'Rouleau City',
        'hot-love-20': 'Combo Hot Love 20 pièces',
        'hot-love-40': 'Combo Hot Love 40 pièces',
        'hot-love-72': 'Combo Hot Love 72 pièces',
        'salmon-tartare': 'Tartare de Saumon',
        'seabass-tartare': 'Tartare de Bar',
        'tuna-tartare': 'Tartare de Thon',
        'salmon-tataki': 'Salmon Tataki',
        'seabass-tataki': 'Sea Bass Tataki',
        'tuna-tataki': 'Tuna Tataki',
        'poke-salmon': 'Bol Poke Saumon',
        'ton': 'Ton',
        'salmon-nigiri': 'Saumon',
        'salmon-avo': 'Saumon Avocat',
        'lavrak': 'Bar',
        'unagi': 'Unagi',
        'cucumber-maki': 'Concombre Maki 6 pièces',
        'maguro-maki': 'Maguro Maki 6 pièces',
        'ebi-maki': 'Ebi Tem 6 pièces',
        'kani-maki': 'Kani Maki 6 pièces',
        'unagi-maki': 'Unagi Maki 6 pièces',
        'avocado-sake': 'Avocat Sake Maki 6 pièces',
        'sake-maki': 'Sake Maki 6 pièces',
        'unagi-avocado': 'Unagi Avocat 6 pièces',
        'salmon-sashimi': 'Set Sashimi Saumon (Saumon 6)',
        'tuna-sashimi': 'Set Sashimi Thon (Thon 6)',
        'lavrak-sashimi': 'Set Sashimi Bar (Bar 6)',
        'salmon-avo-sashimi': 'Set Sashimi Saumon Avocat (Saumon 6, Avocat 6)',
        'sashimi-mix': 'Set Sashimi Mix (Saumon 2, Bar 2, Thon 2, Avocat)',
    }
};

// Current language
let currentLanguage = 'sq';

// Initialize language switcher
document.addEventListener('DOMContentLoaded', function() {
    const langButtons = document.querySelectorAll('.lang-btn');
    
    langButtons.forEach(button => {
        button.addEventListener('click', function() {
            const lang = this.getAttribute('data-lang');
            switchLanguage(lang);
            
            // Update active button
            langButtons.forEach(btn => btn.classList.remove('active'));
            this.classList.add('active');
        });
    });
    
    // Set initial language
    switchLanguage('sq');
});

function switchLanguage(lang) {
    currentLanguage = lang;
    
    // Update all section titles
    document.querySelectorAll('[data-section]').forEach(element => {
        const key = element.getAttribute('data-section');
        if (translations[lang][key]) {
            element.textContent = translations[lang][key];
        }
    });
    
    // Update all item names
    document.querySelectorAll('[data-item]').forEach(element => {
        const key = element.getAttribute('data-item');
        if (translations[lang][key]) {
            element.textContent = translations[lang][key];
        }
    });
    
    // Update footer
    document.querySelectorAll('[data-footer]').forEach(element => {
        const key = element.getAttribute('data-footer');
        if (translations[lang][key]) {
            element.textContent = translations[lang][key];
        }
    });
    
    // Update page language attribute
    document.documentElement.lang = lang;
}